In [2]:
import pandas as pd
import numpy as np

date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [6]:
# Converting to datetime data type

date["date"] = pd.to_datetime(date["date"])
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [7]:
date['date_year'] = date['date'].dt.year
date['date_month'] = date['date'].dt.month
date['date_day'] = date['date'].dt.day
date['date_month_name'] = date['date'].dt.month_name()
date['date_day_name'] = date['date'].dt.day_name()
date['date_day_of_week'] = date['date'].dt.dayofweek
date['date_is_weekend'] = date['date_day_of_week'].apply(lambda x: 1 if x >= 5 else 0)


date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_day_name,date_day_of_week,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday,1,0
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday,2,0
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday,1,0
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday,5,1
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday,6,1

### Extract Time elapsed between date

In [8]:
import datetime

today = datetime.datetime.now()
today

datetime.datetime(2026, 3, 29, 22, 42, 55, 892009)

In [9]:
today - date['date']

0     2301 days 22:42:55.892009
1     2783 days 22:42:55.892009
2     2714 days 22:42:55.892009
3     2416 days 22:42:55.892009
4     2639 days 22:42:55.892009
                 ...
995   2729 days 22:42:55.892009
996   2670 days 22:42:55.892009
997   2518 days 22:42:55.892009
998   2583 days 22:42:55.892009
999   2357 days 22:42:55.892009
Name: date, Length: 1000, dtype: timedelta64[us]

In [11]:
date['date'] = pd.to_datetime(date['date'])