In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("train (1).csv",usecols=['Age','Pclass','Fare','Survived'])
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [3]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [4]:
X = df.drop('Survived',axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [5]:
X_train.head()

     Pclass   Age     Fare
331       1  45.5  28.5000
733       2  23.0  13.0000
382       3  32.0   7.9250
704       3  26.0   7.8542
813       3   6.0  31.2750

In [16]:
knn = KNNImputer(n_neighbors=4, weights='uniform')

X_train_knn = knn.fit_transform(X_train)
X_test_knn = knn.transform(X_test)
pd.DataFrame(X_train_knn,columns=X_train.columns)

     Pclass   Age      Fare
0       1.0  45.5   28.5000
1       2.0  23.0   13.0000
2       3.0  32.0    7.9250
3       3.0  26.0    7.8542
4       3.0   6.0   31.2750
..      ...   ...       ...
707     3.0  21.0    7.6500
708     1.0  41.5   31.0000
709     3.0  41.0   14.1083
710     1.0  14.0  120.0000
711     1.0  21.0   77.2875

[712 rows x 3 columns]

In [17]:
lr = LogisticRegression()
lr.fit(X_train_knn,y_train)
y_pred = lr.predict(X_test_knn)
accuracy_score(y_test,y_pred)

0.7430167597765364

In [18]:
# Comparing with simple imputer
si = SimpleImputer()
X_train_si = si.fit_transform(X_train)
X_test_si = si.transform(X_test)
lr.fit(X_train_si,y_train)
y_pred = lr.predict(X_test_si)
accuracy_score(y_test,y_pred)

0.7374301675977654