In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("customer.csv")
df.sample(5)

    age  gender review education purchased
31   22  Female   Poor    School       Yes
6    18    Male   Good    School        No
19   97    Male   Poor        PG       Yes
7    60  Female   Poor    School       Yes
49   25  Female   Good        UG        No

In [5]:
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop['purchased',axis=1]
y = df['purchased']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)